# Generated by Django 2.1.3 on 2019-11-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets_robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_purchase_requisition_table',
            name='procurement_type',
            field=models.CharField(max_length=50, null=True, verbose_name='采购类型'),
        ),
    ]
