# Generated by Django 2.1.3 on 2019-11-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False, verbose_name='班级id')),
                ('class_code', models.IntegerField(unique=True, verbose_name='班级编号')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('major_name', models.CharField(max_length=50, verbose_name='班级专业')),
                ('school_code', models.IntegerField(verbose_name='班级所在学校')),
                ('class_teacher', models.CharField(max_length=50, verbose_name='班级老师')),
                ('class_state', models.CharField(choices=[('True', '有效'), ('False', '无效')], default='True', max_length=10, verbose_name='有效性')),
                ('begin_time', models.DateTimeField(null=True, verbose_name='开课时间')),
                ('close_time', models.DateTimeField(null=True, verbose_name='关课时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=50, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('course_recommend', models.CharField(max_length=1024, null=True, verbose_name='课程介绍')),
                ('course_state', models.CharField(choices=[('True', '有效'), ('False', '无效')], default='True', max_length=10, verbose_name='有效性')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False, verbose_name='专业id')),
                ('major_code', models.IntegerField(unique=True, verbose_name='专业代码')),
                ('major_name', models.CharField(max_length=50, verbose_name='专业名称')),
                ('school_code', models.IntegerField(unique=True, verbose_name='学校代码')),
                ('major_state', models.CharField(choices=[('True', '有效'), ('False', '无效')], default='True', max_length=10, verbose_name='有效性')),
                ('create_name', models.CharField(max_length=50, verbose_name='创建人')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='报告表')),
                ('report_name', models.CharField(max_length=50, verbose_name='报告名称')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('report_info', models.CharField(max_length=50, null=True, verbose_name='报表内容')),
                ('student_code', models.IntegerField(verbose_name='学号')),
                ('score', models.IntegerField(null=True, verbose_name='得分')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学校id')),
                ('school_code', models.IntegerField(unique=True, verbose_name='学校代码')),
                ('school_name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('school_rank', models.CharField(max_length=10, verbose_name='学校等级')),
                ('school_type', models.CharField(max_length=10, verbose_name='学校类型')),
                ('school_province', models.CharField(max_length=10, verbose_name='省份')),
                ('school_city', models.CharField(max_length=10, verbose_name='城市')),
                ('admin_name', models.IntegerField(verbose_name='教务管理员名称')),
                ('create_name', models.CharField(max_length=50, verbose_name='创建人')),
                ('create_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生id')),
                ('student_code', models.IntegerField(unique=True, verbose_name='学号')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('school_code', models.IntegerField(verbose_name='学生所在学校')),
                ('student_major', models.CharField(max_length=50, verbose_name='学生专业')),
                ('student_class', models.CharField(max_length=50, verbose_name='学生班级')),
                ('phone', models.BigIntegerField(null=True, verbose_name='电话')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('amount', models.IntegerField(default=0, null=True, verbose_name='登入次数')),
                ('sum_time', models.CharField(default='0', max_length=50, null=True, verbose_name='时间总和')),
                ('late_time', models.DateTimeField(null=True, verbose_name='最后登入时间')),
                ('study_time', models.CharField(default='0', max_length=50, null=True, verbose_name='学习时长')),
                ('score', models.IntegerField(null=True, verbose_name='得分')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务id')),
                ('task_name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_recommend', models.CharField(max_length=1000, null=True, verbose_name='任务简介')),
                ('task_state', models.CharField(choices=[('True', '有效'), ('False', '无效')], default='True', max_length=10, verbose_name='有效性')),
                ('course_name', models.CharField(max_length=50, null=True, verbose_name='课程名称')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
