# Generated by Django 2.1.3 on 2019-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('course_recommend', models.CharField(max_length=1024, verbose_name='课程介绍')),
                ('course_state', models.CharField(choices=[('True', '有效'), ('False', '无效')], default='True', max_length=10, verbose_name='有效性')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务id')),
                ('task_name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_recommend', models.CharField(max_length=1000, verbose_name='任务简介')),
                ('task_state', models.CharField(choices=[('True', '有效'), ('False', '无效')], default='True', max_length=10, verbose_name='有效性')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
