# Generated by Django 2.1.3 on 2019-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_task', '0002_course_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course_name',
            field=models.CharField(max_length=50, null=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_recommend',
            field=models.CharField(max_length=1024, null=True, verbose_name='课程介绍'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_recommend',
            field=models.CharField(max_length=1000, null=True, verbose_name='任务简介'),
        ),
    ]
