# Generated by Django 2.1 on 2019-09-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='job_declare_result',
            field=models.CharField(max_length=32, null=True, verbose_name='任务申报结果'),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='corp_name',
            field=models.CharField(max_length=100, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='job_no',
            field=models.CharField(max_length=8, null=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='join_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='mid_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system_config.MakeTaxMidPerson', to_field='phone'),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='province',
            field=models.CharField(max_length=100, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='pwd',
            field=models.CharField(max_length=100, null=True, verbose_name='纳税申报密码'),
        ),
        migrations.AlterField(
            model_name='corpsinfo',
            name='taxpayer_num',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='纳税识别号'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='birth_date',
            field=models.CharField(max_length=100, null=True, verbose_name='*出生日期'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='card_num',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='*证照号码'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='card_type',
            field=models.CharField(max_length=100, null=True, verbose_name='*证照类型'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='corps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_config.CorpsInfo', to_field='taxpayer_num'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name='*性别'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='job_no',
            field=models.CharField(max_length=8, null=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='job_num',
            field=models.CharField(max_length=100, null=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='latest_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='最近添加时间'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='empbaseinfo',
            name='nation',
            field=models.CharField(max_length=100, null=True, verbose_name='*国籍(地区)'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='allowed_minus_num',
            field=models.CharField(max_length=100, null=True, verbose_name='准予扣除的捐赠额'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='annual_bonus',
            field=models.CharField(max_length=100, null=True, verbose_name='企业(职业)年金'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='business_health_insurance',
            field=models.CharField(max_length=100, null=True, verbose_name='商业健康保险'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='child_education',
            field=models.CharField(max_length=100, null=True, verbose_name='累计子女教育'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='continue_education',
            field=models.CharField(max_length=100, null=True, verbose_name='累计继续教育'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='emp_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_config.EmpBaseInfo', to_field='card_num'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='endowment_insurance',
            field=models.CharField(max_length=100, null=True, verbose_name='基本养老保险费'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='housing_fund',
            field=models.CharField(max_length=100, null=True, verbose_name='住房公积金'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='housing_loan',
            field=models.CharField(max_length=100, null=True, verbose_name='累计住房贷款利息'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='housing_rent',
            field=models.CharField(max_length=100, null=True, verbose_name='累计住房租金'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='job_no',
            field=models.CharField(max_length=8, null=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='latest_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='最近添加时间'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='medical_insurance',
            field=models.CharField(max_length=100, null=True, verbose_name='基本医疗保险费'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='note',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='now_free_income',
            field=models.CharField(max_length=100, null=True, verbose_name='本期免税收入'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='now_income',
            field=models.CharField(max_length=100, null=True, verbose_name='*本期收入'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='other',
            field=models.CharField(max_length=100, null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='support_old',
            field=models.CharField(max_length=100, null=True, verbose_name='累计赡养老人'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='tax_delay_sup_old',
            field=models.CharField(max_length=100, null=True, verbose_name='税延养老保险'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='tax_result',
            field=models.CharField(max_length=8, null=True, verbose_name='申报是否成功'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='tax_savings',
            field=models.CharField(max_length=100, null=True, verbose_name='减免税额'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='unemployment_insurance',
            field=models.CharField(max_length=100, null=True, verbose_name='失业保险费'),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='why_error',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='address_city',
            field=models.CharField(max_length=100, null=True, verbose_name='居住地址（市）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='address_detail_loc',
            field=models.CharField(max_length=100, null=True, verbose_name='居住地址（详细地址）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='address_district',
            field=models.CharField(max_length=100, null=True, verbose_name='居住地址（区县）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='address_province',
            field=models.CharField(max_length=100, null=True, verbose_name='居住地址（省）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='bank_account',
            field=models.CharField(max_length=100, null=True, verbose_name='银行账号'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='birth_nation',
            field=models.CharField(max_length=100, null=True, verbose_name='出生国家(地区)'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='chinese_name',
            field=models.CharField(max_length=100, null=True, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='contact_city',
            field=models.CharField(max_length=100, null=True, verbose_name='联系地址（市）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='contact_detail_loc',
            field=models.CharField(max_length=100, null=True, verbose_name='联系地址（详细地址）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='contact_district',
            field=models.CharField(max_length=100, null=True, verbose_name='联系地址（区县）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='contact_province',
            field=models.CharField(max_length=100, null=True, verbose_name='联系地址（省）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='degree',
            field=models.CharField(max_length=100, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='disable_num',
            field=models.CharField(max_length=100, null=True, verbose_name='残疾证号'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='domicile_city',
            field=models.CharField(max_length=100, null=True, verbose_name='户籍所在地（市）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='domicile_detail_loc',
            field=models.CharField(max_length=100, null=True, verbose_name='户籍所在地（详细地址）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='domicile_district',
            field=models.CharField(max_length=100, null=True, verbose_name='户籍所在地（区县）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='domicile_province',
            field=models.CharField(max_length=100, null=True, verbose_name='户籍所在地（省）'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='emp_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_config.EmpBaseInfo', to_field='card_num'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='emp_state',
            field=models.CharField(max_length=100, null=True, verbose_name='*人员状态'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='first_in_nation_date',
            field=models.CharField(max_length=100, null=True, verbose_name='首次入境时间'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='hero_num',
            field=models.CharField(max_length=100, null=True, verbose_name='烈属证号'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='individual_invest',
            field=models.CharField(max_length=100, null=True, verbose_name='个人投资额'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='individual_invest_proportion',
            field=models.CharField(max_length=100, null=True, verbose_name='个人投资比例(%)'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='is_alone',
            field=models.CharField(max_length=100, null=True, verbose_name='是否孤老'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='is_disabled',
            field=models.CharField(max_length=100, null=True, verbose_name='是否残疾'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='is_hero',
            field=models.CharField(max_length=100, null=True, verbose_name='是否烈属'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='is_out_nation',
            field=models.CharField(max_length=100, null=True, verbose_name='是否境外人员'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='job_date',
            field=models.CharField(max_length=100, null=True, verbose_name='任职受雇从业日期'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='job_no',
            field=models.CharField(max_length=8, null=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='job_type',
            field=models.CharField(max_length=100, null=True, verbose_name='*任职受雇从业类型'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='latest_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='最近添加时间'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='leave_nation_date',
            field=models.CharField(max_length=100, null=True, verbose_name='预计离境时间'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='note',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='open_bank',
            field=models.CharField(max_length=100, null=True, verbose_name='开户银行'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='other_card_num',
            field=models.CharField(max_length=100, null=True, verbose_name='其他证照号码'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='other_card_type',
            field=models.CharField(max_length=100, null=True, verbose_name='其他证照类型'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='quit_date',
            field=models.CharField(max_length=100, null=True, verbose_name='离职日期'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='tax_relate_matter',
            field=models.CharField(max_length=100, null=True, verbose_name='涉税事由'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='tax_result',
            field=models.CharField(max_length=8, null=True, verbose_name='申报是否成功'),
        ),
        migrations.AlterField(
            model_name='emptaxinfo',
            name='why_error',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='corp_base_id',
            field=models.IntegerField(null=True, verbose_name='企业基础信息id'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='emp_base_id',
            field=models.IntegerField(null=True, verbose_name='员工基础信息id'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='isa_job_no',
            field=models.CharField(max_length=200, null=True, verbose_name='艺赛旗任务编号'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_end_time',
            field=models.CharField(max_length=32, null=True, verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_name',
            field=models.CharField(max_length=32, null=True, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_result',
            field=models.CharField(max_length=32, null=True, verbose_name='任务填报结果'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_start_time',
            field=models.CharField(max_length=32, null=True, verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_status',
            field=models.CharField(max_length=32, null=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_use_time',
            field=models.CharField(max_length=32, null=True, verbose_name='任务用时'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='mid_person_id',
            field=models.IntegerField(null=True, verbose_name='中间人id'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='priority_sort',
            field=models.CharField(max_length=32, null=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='why_error',
            field=models.CharField(max_length=32, null=True, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='consultant_name',
            field=models.CharField(max_length=100, null=True, verbose_name='顾问姓名'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='consultant_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='顾问手机号'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='consultant_weChat',
            field=models.CharField(max_length=100, null=True, verbose_name='顾问微信号'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='consultant_weChat_pwd',
            field=models.CharField(max_length=100, null=True, verbose_name='顾问微信密码'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='guest_weChat',
            field=models.CharField(max_length=100, null=True, verbose_name='客户微信号'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='job_no',
            field=models.CharField(max_length=8, null=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='join_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='phone',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='maketaxmidperson',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name='职位'),
        ),
    ]
