# Generated by Django 2.1 on 2019-09-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_auto_20190907_1139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
