# Generated by Django 2.1 on 2019-09-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_auto_20190907_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
