# Generated by Django 2.1 on 2019-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='why_error',
        ),
        migrations.AddField(
            model_name='joblist',
            name='declare_error',
            field=models.CharField(max_length=32, null=True, verbose_name='申报错误原因'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='job_declare_status',
            field=models.CharField(max_length=32, null=True, verbose_name='任务是否申报'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='report_error',
            field=models.CharField(max_length=32, null=True, verbose_name='填报错误原因'),
        ),
    ]
