# Generated by Django 2.1 on 2019-09-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0006_job_list_summary_job_error'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maketaxmidperson',
            table='maketaxmidperson',
        ),
    ]
