# Generated by Django 2.1 on 2019-09-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0007_auto_20190909_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='empsalary',
            name='tax_rate',
            field=models.CharField(max_length=200, null=True, verbose_name='税率'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_result',
            field=models.CharField(default='失败', max_length=32, null=True, verbose_name='任务填报结果'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='report_error',
            field=models.CharField(default='未填报', max_length=32, null=True, verbose_name='填报错误原因'),
        ),
    ]
