# Generated by Django 2.1 on 2019-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0008_auto_20190910_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='job_result',
            field=models.CharField(default='1115', max_length=32, null=True, verbose_name='任务填报结果'),
        ),
    ]
