# Generated by Django 2.1.3 on 2019-11-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_invoice_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_name', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('gmt_create', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('purchase_number', models.CharField(max_length=20, null=True, verbose_name='请购单编号')),
                ('contract_number', models.CharField(max_length=20, null=True, verbose_name='采购合同编号')),
                ('incoive_number', models.CharField(max_length=20, null=True, verbose_name='发票号码')),
                ('reimbursement_type', models.CharField(max_length=20, null=True, verbose_name='报销类别')),
                ('reimbursement_money', models.CharField(max_length=20, null=True, verbose_name='发票号码')),
                ('money_details', models.CharField(max_length=20, null=True, verbose_name='价格')),
                ('supplier_name', models.CharField(max_length=20, null=True, verbose_name='供应商信息')),
                ('application_date', models.CharField(max_length=20, null=True, verbose_name='申请日期')),
                ('application', models.CharField(max_length=20, null=True, verbose_name='申请人')),
                ('application_sector', models.CharField(max_length=20, null=True, verbose_name='申请部门')),
                ('department_head', models.CharField(max_length=20, null=True, verbose_name='部门领导')),
                ('company_head', models.CharField(max_length=20, null=True, verbose_name='公司领导')),
            ],
            options={
                'db_table': 'purchase_invoice_table',
            },
        ),
        migrations.CreateModel(
            name='purchase_payment_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_name', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('gmt_create', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('purchase_number', models.CharField(max_length=20, null=True, verbose_name='请购单编号')),
                ('contract_number', models.CharField(max_length=20, null=True, verbose_name='采购合同编号')),
                ('payment_reason', models.CharField(max_length=20, null=True, verbose_name='付款事由')),
                ('payment_money', models.CharField(max_length=20, null=True, verbose_name='付款事由')),
                ('payment_type', models.CharField(max_length=20, null=True, verbose_name='付款类型')),
                ('payment_date', models.CharField(max_length=20, null=True, verbose_name='支付日期')),
                ('payment_object', models.CharField(max_length=20, null=True, verbose_name='支付对象')),
                ('payment_bank', models.CharField(max_length=20, null=True, verbose_name='开户行')),
                ('bank_account', models.CharField(max_length=20, null=True, verbose_name='银行账号')),
                ('application_date', models.CharField(max_length=20, null=True, verbose_name='银行账号')),
                ('application', models.CharField(max_length=20, null=True, verbose_name='申请人')),
                ('application_sector', models.CharField(max_length=20, null=True, verbose_name='申请部门')),
                ('department_head', models.CharField(max_length=20, null=True, verbose_name='部门领导')),
                ('company_head', models.CharField(max_length=20, null=True, verbose_name='公司领导')),
            ],
            options={
                'db_table': 'purchase_payment_table',
            },
        ),
        migrations.CreateModel(
            name='purchase_warehousing_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('gmt_create', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('purchase_number', models.CharField(max_length=20, null=True, verbose_name='请购单编号')),
                ('contract_number', models.CharField(max_length=20, null=True, verbose_name='合同编号')),
                ('warehouse_number', models.CharField(max_length=20, null=True, verbose_name='仓库编号')),
                ('warehouse_date', models.CharField(max_length=20, null=True, verbose_name='入库日期')),
                ('application', models.CharField(max_length=20, null=True, verbose_name='点验人员')),
            ],
            options={
                'db_table': 'purchase_warehousing_table',
            },
        ),
    ]
